### ISSUE TITLE
TypeError: modelv2() got an unexpected keyword argument 'device'

### ISSUE THREAD

**Issue by lauraslopes** [wonbeomjang/mobile-hair-segmentation-pytorch#22]
Hi, I'm getting this error by running webcam.py or predict.py. When I run with modelv1 it raises a similar error. Can you help me find a solution?

Traceback (most recent call last):
  File "/home/hub/mobile-hair-segmentation-pytorch/webcam.py", line 72, in <module>
    net = build_model(args.model_version, args.quantize, args.model_path, device)
  File "/home/hub/mobile-hair-segmentation-pytorch/webcam.py", line 39, in build_model
    net = modelv2(pretrained=True, device=device).to(device)
TypeError: modelv2() got an unexpected keyword argument 'device'

Thanks!

**Comment by PAnuragReddy** [comment]
Remove device=device from parameters. It worked for me.
