### ISSUE TITLE
 DefaultCPUAllocator: not enough memory: you tried to allocate 3699376128 bytes. Buy new RAM!

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [wonbeomjang/mobile-hair-segmentation-pytorch#6]
Hello,

I am trying to run 'main.py' file by creating a dataset of Figaro dataset. I am getting the following error. Please help..

(env_cv_dlib_36) C:\Users\Mayank\PycharmProjects\init_real_time_deep_hair_matting>python main.py
[*] Load checkpoint in  checkpoints
[!] No checkpoint in  checkpoints
C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    main(config)
  File "main.py", line 30, in main
    trainer.train()
  File "C:\Users\Mayank\PycharmProjects\init_real_time_deep_hair_matting\src\train.py", line 79, in train
    pred = self.net(image)
  File "C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Mayank\PycharmProjects\init_real_time_deep_hair_matting\model\model.py", line 126, in forward
    decode_layer5 = self.decode_layer5(decode_layer4)
  File "C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\modules\conv.py", line 345, in forward
    return self.conv2d_forward(input, self.weight)
  File "C:\ProgramData\Anaconda3\envs\env_cv_dlib_36\lib\site-packages\torch\nn\modules\conv.py", line 342, in conv2d_forward
    self.padding, self.dilation, self.groups)
**RuntimeError: [enforce fail at ..\c10\core\CPUAllocator.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 3699376128 bytes. Buy new RAM!**

**Comment by wonbeomjang** [comment]
This problem is caused by insufficient computer memory. 
If you reduce the batch size enough on "mobile-hair-segmentation-pytorch/config/config.py", training  will be work.

Training takes at least 5 hour on GPU(GTX 1080TI) and takes maybe 4~5GB GPU memory
